services:
  techbrain-wbo:
    container_name: techbrain-wbo
    image: techbrain-wbo
    build:
      context: .
    restart: unless-stopped
    ports:
      - "5002:80"
    environment:
      SAVE_BOARDS: "true"
      WBO_HISTORY_DIR: /opt/app/server-data
    volumes:
      - ./server-data:/opt/app/server-data

